namespace Origo.Bifrost.Timesheets;

/// <summary>
/// Full permission set for the Bifrost Timesheets connector. Grants execute
/// rights on every Clockify object: the integration table, the HTTP client,
/// request helper, secret, setup, workspace and retention-policy management,
/// install, the setup card, secret dialog, workspace lookup and integration list
/// pages, the per-domain help codeunits and all message-type implementation codeunits.
/// </summary>
permissionset 70009200 "BIFROST Timeshts ori"
{
    Access = Public;
    Assignable = true;
    Caption = 'Bifrost Timesheets', MaxLength = 30, Comment = 'is-IS=Bifröst tímaskýrslur';

    Permissions =
        tabledata "Clockify Setup ori" = RIMD,
        tabledata "Clockify Integration ori" = RIMD,
        tabledata "Clockify Webhook ori" = RIMD,
        codeunit "Clockify Secret Mgt ori" = X,
        codeunit "Clockify Setup Mgt ori" = X,
        codeunit "Clockify Webhook Mgt ori" = X,
        codeunit "Clockify Webhook Handler ori" = X,
        codeunit "Clockify Workspace Mgt ori" = X,
        codeunit "Clockify Reten. Policy ori" = X,
        codeunit "Clockify Integration Gate ori" = X,
        codeunit "Clockify Client ori" = X,
        codeunit "Clockify Request Mgt ori" = X,
        codeunit "Clockify Help Builder ori" = X,
        codeunit "Clockify Workspace Help ori" = X,
        codeunit "Clockify Client Help ori" = X,
        codeunit "Clockify Project Help ori" = X,
        codeunit "Clockify Task Help ori" = X,
        codeunit "Clockify Tag Help ori" = X,
        codeunit "Clockify TimeEntry Help ori" = X,
        codeunit "Clockify Install ori" = X,
        codeunit "Clockify Time Entry Sync ori" = X,
        codeunit "Clockify Event Subscribers ori" = X,
        codeunit "Clockify Help Get Impl ori" = X,
        codeunit "Clockify WrkspaceList Impl ori" = X,
        codeunit "Clockify User Current Impl ori" = X,
        codeunit "Clockify User List Impl ori" = X,
        codeunit "Clockify Client List Impl ori" = X,
        codeunit "Clockify Client Get Impl ori" = X,
        codeunit "Clockify ClientCreate Impl ori" = X,
        codeunit "Clockify ClientUpdate Impl ori" = X,
        codeunit "Clockify ClientDelete Impl ori" = X,
        codeunit "Clockify Project List Impl ori" = X,
        codeunit "Clockify Project Get Impl ori" = X,
        codeunit "Clockify ProjCreate Impl ori" = X,
        codeunit "Clockify ProjUpdate Impl ori" = X,
        codeunit "Clockify ProjDelete Impl ori" = X,
        codeunit "Clockify Task List Impl ori" = X,
        codeunit "Clockify Task Create Impl ori" = X,
        codeunit "Clockify Task Update Impl ori" = X,
        codeunit "Clockify Task Delete Impl ori" = X,
        codeunit "Clockify Tag List Impl ori" = X,
        codeunit "Clockify Tag Create Impl ori" = X,
        codeunit "Clockify Tag Update Impl ori" = X,
        codeunit "Clockify Tag Delete Impl ori" = X,
        codeunit "Clockify TEntryList Impl ori" = X,
        codeunit "Clockify TEntryGet Impl ori" = X,
        codeunit "Clockify TEntryCreate Impl ori" = X,
        codeunit "Clockify TEntryUpdate Impl ori" = X,
        codeunit "Clockify TEntryDelete Impl ori" = X,
        codeunit "Clockify TEntrySync Impl ori" = X,
        codeunit "Clockify TEntryRange Impl ori" = X,
        codeunit "Clockify TimeEntry Parse ori" = X,
        codeunit "Clockify TimeEntry Fetch ori" = X,
        codeunit "Clockify SyncAllUsers Impl ori" = X,
        codeunit "Clockify TimeSheet Sync ori" = X,
        codeunit "Clockify TSheetSync Impl ori" = X,
        codeunit "Clockify TSheetRange Impl ori" = X,
        codeunit "Clockify TimeSheet Mgt ori" = X,
        codeunit "Clockify TimeSheet Help ori" = X,
        codeunit "Clockify TSheetCreate Impl ori" = X,
        codeunit "Clockify TSheetApprv Impl ori" = X,
        codeunit "Clockify TSheetReject Impl ori" = X,
        codeunit "Clockify TSheetReopen Impl ori" = X,
        codeunit "Clockify TSheetPost Impl ori" = X,
        codeunit "Clockify TSheetArch Impl ori" = X,
        codeunit "Clockify Archive Sync ori" = X,
        codeunit "Clockify CurrencyList Impl ori" = X,
        codeunit "Clockify UserGrpList Impl ori" = X,
        codeunit "Clockify CustFldList Impl ori" = X,
        codeunit "Clockify Help Overview Sub ori" = X,
        codeunit "Clockify ReqLog Masker ori" = X,
        page "Timesheets Setup ori" = X,
        page "Clockify Set Secret Dialog ori" = X,
        page "Clockify Workspace Lookup ori" = X,
        page "Clockify Integration List ori" = X,
        page "Clockify Webhooks ori" = X;
}
